@server = http://localhost:3000

# 게시글 조회
GET {{server}}/blog

### 게시글 생성
POST {{server}}/blog
content-Type: application/json

{
    "title": "안녕",
    "content": "블라블라",
    "name": "이름"
}

### 특정 게시글 조회
GET {{server}}/blog/647619488b7bfece08f47651

### 게시글 삭제
DELETE {{server}}/blog/647619488b7bfece08f47651

### 게시글 수정
PUT {{server}}/blog/647618d831a8662a12ea3894
Content-Type: application/json

{
    "title": "타이틀 수정3",
    "content": "본문수정3",
    "name": "김일남"
}
